networks:
  misp_network:
    driver: bridge

services:
  mail:
    image: ixdotai/smtp
    environment:
      - "SMARTHOST_ADDRESS=${SMARTHOST_ADDRESS}"
      - "SMARTHOST_PORT=${SMARTHOST_PORT}"
      - "SMARTHOST_USER=${SMARTHOST_USER}"
      - "SMARTHOST_PASSWORD=${SMARTHOST_PASSWORD}"
      - "SMARTHOST_ALIASES=${SMARTHOST_ALIASES}"
    networks:
      - misp_network

  redis:
    image: valkey/valkey:7.2
    command: "--save '' --requirepass '${REDIS_PASSWORD:-redispassword}'"
    networks:
      - misp_network
    healthcheck:
      test: "valkey-cli -a '${REDIS_PASSWORD:-redispassword}' -p ${REDIS_PORT:-6379} ping | grep -q PONG || exit 1"
      interval: 2s
      timeout: 1s
      retries: 3
      start_period: 5s
      start_interval: 5s

  db:
    image: mariadb:10.11
    restart: always
    environment:
      - "MYSQL_USER=${MYSQL_USER:-misp}"
      - "MYSQL_PASSWORD=${MYSQL_PASSWORD:-example}"
      - "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-password}"
      - "MYSQL_DATABASE=${MYSQL_DATABASE:-misp}"
    networks:
      - misp_network
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: mysqladmin --user=$$MYSQL_USER --password=$$MYSQL_PASSWORD status
      interval: 2s
      timeout: 1s
      retries: 3
      start_period: 30s
      start_interval: 5s

  misp-core:
    image: ghcr.io/misp/misp-docker/misp-core:${CORE_RUNNING_TAG:-latest}
    cap_add:
      - AUDIT_WRITE
    build:
      context: core/.
      args:
          - CORE_TAG=${CORE_TAG:?Missing .env file, see README.md for instructions}
          - CORE_COMMIT=${CORE_COMMIT}
          - PHP_VER=${PHP_VER:?Missing .env file, see README.md for instructions}
    depends_on:
      redis:
        condition: service_healthy
      db:
        condition: service_healthy
      misp-modules:
        condition: service_healthy
    healthcheck:
      test: curl -ks ${BASE_URL:-https://localhost}/users/heartbeat > /dev/null || exit 1
      interval: 2s
      timeout: 1s
      retries: 3
      start_period: 30s
      start_interval: 30s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.misp.rule=Host(`${MISP_DOMAIN}`)"
      - "traefik.http.routers.misp.entrypoints=websecure"
      - "traefik.http.routers.misp.tls.certresolver=myresolver"
    volumes:
      - "./configs/:/var/www/MISP/app/Config/"
      - "./logs/:/var/www/MISP/app/tmp/logs/"
      - "./files/:/var/www/MISP/app/files/"
      - "./ssl/:/etc/nginx/certs/"
      - "./gnupg/:/var/www/MISP/.gnupg/"
    networks:
      - misp_network

  misp-modules:
    image: ghcr.io/misp/misp-docker/misp-modules:${MODULES_RUNNING_TAG:-latest}
    build:
      context: modules/.
      args:
        - MODULES_TAG=${MODULES_TAG:?Missing .env file, see README.md for instructions}
    environment:
      - "REDIS_BACKEND=${REDIS_HOST:-redis}"
      - "REDIS_PORT=${REDIS_PORT:-6379}"
      - "REDIS_PW=${REDIS_PASSWORD:-redispassword}"
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - misp_network
    healthcheck:
      test: "/bin/bash -c '</dev/tcp/localhost/6666'"
      interval: 2s
      timeout: 1s
      retries: 3
      start_period: 5s
      start_interval: 5s

volumes:
  mysql_data:
